In [4]:
import numpy as np

In [3]:
np

In [5]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [7]:
np.full(10, 3.14)

array([3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14])

In [9]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [10]:
a[2]

np.int64(3)

In [11]:
a[2] = 10

In [12]:
a[2]

np.int64(10)

In [13]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [21]:
np.linspace(10, 100, 4)

array([ 10.,  40.,  70., 100.])

In [23]:
np.zeros((5, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [26]:
n = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
n[0, 1] = 20

In [29]:
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [30]:
n[0]

array([ 1, 20,  3])

In [31]:
n[2] = [1,1,1]

In [32]:
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 1,  1,  1]])

In [37]:
n[:, 2] = [0,1,2]

In [38]:
n[:,2]

array([0, 1, 2])

In [39]:
n

array([[ 1, 20,  0],
       [ 4,  5,  1],
       [ 1,  1,  2]])

In [42]:
np.random.seed(2)
np.random.rand(5, 2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [44]:
np.random.seed(2)
np.random.randn(5, 2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [45]:
np.random.seed(2)
np.random.randint(low=0, high=100, size=(5, 2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

In [46]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [51]:
10 + (a * 2)

array([10, 12, 14, 16, 18])

In [56]:
b = (10 + (a * 2)) ** 2 / 100
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [57]:
a + b

array([1.  , 2.44, 3.96, 5.56, 7.24])

In [58]:
a >= 2

array([False, False,  True,  True,  True])

In [59]:
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [60]:
a > b

array([False, False,  True,  True,  True])

In [63]:
a[a > b]

array([2, 3, 4])

In [64]:
a

array([0, 1, 2, 3, 4])

In [65]:
a.min()

np.int64(0)

In [66]:
a.max()

np.int64(4)

In [67]:
a.sum()

np.int64(10)

In [68]:
a.mean()

np.float64(2.0)

In [69]:
a.std()

np.float64(1.4142135623730951)

In [5]:
v = np.array([2, 4, 5, 6])

In [13]:
u = np.array([1, 0, 0, 2])
u.shape

(4,)

In [9]:
def vector_vector_mult(u, v):
    assert u.shape[0] == v.shape[0]
    n = u.shape[0]
    result = 0.0
    for i in range(n):
        result = result + u[i] * v[i]
    return result

In [10]:
vector_vector_mult(u, v)

np.float64(14.0)

In [14]:
u.dot(v)

np.int64(14)

In [17]:
U = np.array([[2, 4, 5 ,6],
              [1, 2, 1, 2],
              [3, 1, 2, 1]])
U
U.shape

(3, 4)

In [20]:
def matrix_vector_mult(U, v):
    assert U.shape[1] == v.shape[0]
    num_rows = U.shape[0]
    result = np.zeros(num_rows)
    for i in range(num_rows):
        result[i] = vector_vector_mult(U[i], v)
    return result

In [21]:
matrix_vector_mult(U, v)

array([81., 27., 26.])

In [23]:
U.dot(v)

array([81, 27, 26])

In [29]:
V = np.array([[1, 1, 2],
              [0, .5, 1],
              [0, 2, 1],
              [2, 1, 0]])
V

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [25]:
def matrix_matrix_mult(U, V):
    assert U.shape[1] == V.shape[0]
    
    num_rows = U.shape[0]
    num_cols = V.shape[1]
    result = np.zeros((num_rows, num_cols))

    for i in range(num_cols):
        vi = V[:, i]
        Uvi = matrix_vector_mult(U, vi)
        result[:, i] = Uvi
    return result

In [30]:
matrix_matrix_mult(U, V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [31]:
U.dot(V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [35]:
I = np.eye(3)

In [36]:
V

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [37]:
V.dot(I)

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [41]:
Vs = V[:3]
Vs

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ]])

In [44]:
Vs_inv = np.linalg.inv(Vs)
Vs_inv

array([[ 1.        , -2.        ,  0.        ],
       [ 0.        , -0.66666667,  0.66666667],
       [ 0.        ,  1.33333333, -0.33333333]])

In [45]:
Vs_inv.dot(Vs)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [4]:
import pandas as pd

In [5]:
data = [
    ['Nissan', 'Stanza', 1991, 138, 4, 'MANUAL', 'sedan', 2000],
    ['Hyundai', 'Sonata', 2017, None, 4, 'AUTOMATIC', 'Sedan', 27150],
    ['Lotus', 'Elise', 2010, 218, 4, 'MANUAL', 'convertible', 54990],
    ['GMC', 'Acadia',  2017, 194, 4, 'AUTOMATIC', '4dr SUV', 34450],
    ['Nissan', 'Frontier', 2017, 261, 6, 'MANUAL', 'Pickup', 32340],
]
 
columns = [
    'Make', 'Model', 'Year', 'Engine HP', 'Engine Cylinders',
    'Transmission Type', 'Vehicle_Style', 'MSRP'
]
 
pd.DataFrame(data)

         0         1     2      3  4          5            6      7
0   Nissan    Stanza  1991  138.0  4     MANUAL        sedan   2000
1  Hyundai    Sonata  2017    NaN  4  AUTOMATIC        Sedan  27150
2    Lotus     Elise  2010  218.0  4     MANUAL  convertible  54990
3      GMC    Acadia  2017  194.0  4  AUTOMATIC      4dr SUV  34450
4   Nissan  Frontier  2017  261.0  6     MANUAL       Pickup  32340

In [6]:
df = pd.DataFrame(data, columns=columns)

In [7]:
df.head()

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

In [7]:
df.head(n=2)

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150

In [8]:
df.Make

0     Nissan
1    Hyundai
2      Lotus
3        GMC
4     Nissan
Name: Make, dtype: str

In [9]:
df['Make']

0     Nissan
1    Hyundai
2      Lotus
3        GMC
4     Nissan
Name: Make, dtype: str

In [10]:
df[['Make', 'Model', 'MSRP']]

      Make     Model   MSRP
0   Nissan    Stanza   2000
1  Hyundai    Sonata  27150
2    Lotus     Elise  54990
3      GMC    Acadia  34450
4   Nissan  Frontier  32340

In [11]:
df['id'] = [1, 2, 3, 4, 5]

In [12]:
df['id']

0    1
1    2
2    3
3    4
4    5
Name: id, dtype: int64

In [13]:
df['id'] = [10, 20, 30, 40, 50]
df['id']

0    10
1    20
2    30
3    40
4    50
Name: id, dtype: int64

In [14]:
del df['id']

In [15]:
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

In [16]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [17]:
df.Make

0     Nissan
1    Hyundai
2      Lotus
3        GMC
4     Nissan
Name: Make, dtype: str

In [18]:
df.Make.index

RangeIndex(start=0, stop=5, step=1)

In [20]:
df.loc[1]

Make                   Hyundai
Model                   Sonata
Year                      2017
Engine HP                  NaN
Engine Cylinders             4
Transmission Type    AUTOMATIC
Vehicle_Style            Sedan
MSRP                     27150
Name: 1, dtype: object

In [21]:
df.loc[[1, 2]]

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990

In [22]:
df.index = ['a', 'b', 'c', 'd', 'e']
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
a,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
b,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
c,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
d,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
e,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

In [23]:
df.loc['a']

Make                 Nissan
Model                Stanza
Year                   1991
Engine HP             138.0
Engine Cylinders          4
Transmission Type    MANUAL
Vehicle_Style         sedan
MSRP                   2000
Name: a, dtype: object

In [24]:
df.loc[['a', 'b']]

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
a,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
b,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150

In [25]:
df.iloc[1]

Make                   Hyundai
Model                   Sonata
Year                      2017
Engine HP                  NaN
Engine Cylinders             4
Transmission Type    AUTOMATIC
Vehicle_Style            Sedan
MSRP                     27150
Name: b, dtype: object

In [29]:
df = df.reset_index(drop=True)

In [32]:
df['Engine HP'] * 2

0    276.0
1      NaN
2    436.0
3    388.0
4    522.0
Name: Engine HP, dtype: float64

In [33]:
df['Year'] >= 2015

0    False
1     True
2    False
3     True
4     True
Name: Year, dtype: bool

In [36]:
df[
    df['Make'] == 'Nissan'
    ]

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

In [37]:
df[
    ( df['Make'] == 'Nissan') & (df['Year'] >= 2015)
]

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

In [8]:
df['Vehicle_Style']

0          sedan
1          Sedan
2    convertible
3        4dr SUV
4         Pickup
Name: Vehicle_Style, dtype: str

In [9]:
df['Vehicle_Style'].str.lower()

0          sedan
1          sedan
2    convertible
3        4dr suv
4         pickup
Name: Vehicle_Style, dtype: str

In [10]:
'machine learning zoomcamp'.replace(' ', '_')

'machine_learning_zoomcamp'

In [11]:
df['Vehicle_Style'].str.replace(' ', '_')

0          sedan
1          Sedan
2    convertible
3        4dr_SUV
4         Pickup
Name: Vehicle_Style, dtype: str

In [12]:
df['Vehicle_Style'].str.replace(' ', '_').str.lower()

0          sedan
1          sedan
2    convertible
3        4dr_suv
4         pickup
Name: Vehicle_Style, dtype: str

In [13]:
df['Vehicle_Style'] = df['Vehicle_Style'].str.replace(' ', '_').str.lower()

In [14]:
df['Vehicle_Style']

0          sedan
1          sedan
2    convertible
3        4dr_suv
4         pickup
Name: Vehicle_Style, dtype: str

In [15]:
df.MSRP

0     2000
1    27150
2    54990
3    34450
4    32340
Name: MSRP, dtype: int64

In [16]:
df.MSRP.min()

np.int64(2000)

In [17]:
df.MSRP.max()

np.int64(54990)

In [18]:
df.MSRP.mean()

np.float64(30186.0)

In [19]:
df.MSRP.describe()

count        5.000000
mean     30186.000000
std      18985.044904
min       2000.000000
25%      27150.000000
50%      32340.000000
75%      34450.000000
max      54990.000000
Name: MSRP, dtype: float64

In [20]:
df.describe()

              Year  Engine HP  Engine Cylinders          MSRP
count     5.000000    4.00000          5.000000      5.000000
mean   2010.400000  202.75000          4.400000  30186.000000
std      11.260551   51.29896          0.894427  18985.044904
min    1991.000000  138.00000          4.000000   2000.000000
25%    2010.000000  180.00000          4.000000  27150.000000
50%    2017.000000  206.00000          4.000000  32340.000000
75%    2017.000000  228.75000          4.000000  34450.000000
max    2017.000000  261.00000          6.000000  54990.000000

In [21]:
df.describe().round(2)

          Year  Engine HP  Engine Cylinders      MSRP
count     5.00       4.00              5.00      5.00
mean   2010.40     202.75              4.40  30186.00
std      11.26      51.30              0.89  18985.04
min    1991.00     138.00              4.00   2000.00
25%    2010.00     180.00              4.00  27150.00
50%    2017.00     206.00              4.00  32340.00
75%    2017.00     228.75              4.00  34450.00
max    2017.00     261.00              6.00  54990.00

In [22]:
df['Make'].nunique()

4

In [23]:
df.nunique()

Make                 4
Model                5
Year                 3
Engine HP            4
Engine Cylinders     2
Transmission Type    2
Vehicle_Style        4
MSRP                 5
dtype: int64

In [24]:
df.isnull()

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,False,False,False,False,False,False,False,False
1,False,False,False,True,False,False,False,False
2,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False

In [25]:
df.isnull().sum()

Make                 0
Model                0
Year                 0
Engine HP            1
Engine Cylinders     0
Transmission Type    0
Vehicle_Style        0
MSRP                 0
dtype: int64

In [26]:
'''
SELECT
    transmission_type,
    AVG(MSRP)
FROM
    cars
GROUP BY
    transmission_type
'''

'\nSELECT\n    transmission_type,\n    AVG(MSRP)\nFROM\n    cars\nGROUP BY\n    transmission_type\n'

In [27]:
df.groupby('Transmission Type').MSRP.mean()

Transmission Type
AUTOMATIC    30800.000000
MANUAL       29776.666667
Name: MSRP, dtype: float64

In [28]:
df['MSRP'].values

array([ 2000, 27150, 54990, 34450, 32340])

In [29]:
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,sedan,27150
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr_suv,34450
4,Nissan,Frontier,2017,261.0,6,MANUAL,pickup,32340

In [31]:
df.to_dict()

{'Make': {0: 'Nissan', 1: 'Hyundai', 2: 'Lotus', 3: 'GMC', 4: 'Nissan'},
 'Model': {0: 'Stanza', 1: 'Sonata', 2: 'Elise', 3: 'Acadia', 4: 'Frontier'},
 'Year': {0: 1991, 1: 2017, 2: 2010, 3: 2017, 4: 2017},
 'Engine HP': {0: 138.0, 1: nan, 2: 218.0, 3: 194.0, 4: 261.0},
 'Engine Cylinders': {0: 4, 1: 4, 2: 4, 3: 4, 4: 6},
 'Transmission Type': {0: 'MANUAL',
  1: 'AUTOMATIC',
  2: 'MANUAL',
  3: 'AUTOMATIC',
  4: 'MANUAL'},
 'Vehicle_Style': {0: 'sedan',
  1: 'sedan',
  2: 'convertible',
  3: '4dr_suv',
  4: 'pickup'},
 'MSRP': {0: 2000, 1: 27150, 2: 54990, 3: 34450, 4: 32340}}